apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blackbox-exporter
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://github.com/prometheus-community/helm-charts.git
      path: charts/prometheus-blackbox-exporter
      helm:
        valueFiles:
          - $values/blackbox-exporter/blackbox-exporter-values.yml
    - repoURL: https://github.com/TurosIgor/argocd-practice.git
      ref: values
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true