serviceMonitor:
  selfMonitor:
    enabled: true
    path: /metrics
    scheme: http
    interval: 30s
    scrapeTimeout: 30s
  enabled: true
  scheme: http
  path: /probe
  targets:
    - name: taboo-frontend
      url: frontend-lb.taboo.svc
      interval: 30s
      scrapeTimeout: 30s
      module: http_2xx
    - name: taboo-backend
      url: backend-svc.taboo.svc:3000/api/v2/word
      interval: 30s
      scrapeTimeout: 30s
      module: http_2xx
    - name: taboo-database
      url: frontend-lb.taboo.svc
      interval: 30s
      scrapeTimeout: 30s
      module: http_2xx
prometheusRule:
  enabled: true