serviceMonitor:
  selfMonitor:
    enabled: true
    path: /metrics
    scheme: http
    interval: 30s
    scrapeTimeout: 30s
  enabled: true
  scheme: http
  path: /probe
  defaults:
    additionalRelabeling:
      - source_labels: [__address__]
        action: replace
        target_label: __param_target
      - source_labels: [__param_target]
        action: replace
        target_label: instance
      - target_label: __address__
        action: replace
        replacement: blackbox-exporter-prometheus-blackbox-exporter.prometheus.svc:9115
  targets:
    - name: taboo-frontend
      url: frontend-lb.taboo.svc
      interval: 30s
      scrapeTimeout: 30s
      module: http_2xx
    - name: taboo-backend
      url: backend-svc.taboo.svc:3000/api/v2/word
      interval: 30s
      scrapeTimeout: 30s
      module: http_2xx
    - name: taboo-database
      url: frontend-lb.taboo.svc
      interval: 30s
      scrapeTimeout: 30s
      module: http_2xx
prometheusRule:
  enabled: true
  namespace: prometheus
  rules:
    - alert: BlackboxProbeFailed
      expr: probe_success == 0
      for: 0m
      labels:
        severity: critical
      
    - alert: BlackboxSlowProbe
      expr: avg_over_time(probe_duration_seconds[1m]) > 1
      for: 1m
      labels:
        severity: warning