serviceMonitor:
  selfMonitor:
    enabled: true
    path: /metrics
    scheme: http
    interval: 30s
    scrapeTimeout: 30s
  enabled: true
  scheme: http
  path: /probe
  targets:
    - name: taboo-frontend
      url: frontend-lb.taboo.svc
      interval: 30s
      scrapeTimeout: 30s
      module: http_2xx
    - name: taboo-backend
      url: backend-svc.taboo.svc:3000/api/v2/word
      interval: 30s
      scrapeTimeout: 30s
      module: http_2xx
    - name: taboo-database
      url: mongo-svc.taboo.svc:27017
      interval: 30s
      scrapeTimeout: 30s
      module: http_2xx
prometheusRule:
  enabled: true
  namespace: monitoring
  rules:
    - alert: BlackboxProbeFailed
      annotations:
        description: Probe for {{ $labels.instance }} failed.
      expr: probe_success == 0
      for: 0m
      labels:
        severity: critical
      
    - alert: BlackboxSlowProbe
      annotations:
        description: Probe for {{ $labels.instance }} timed out.
      expr: avg_over_time(probe_duration_seconds[1m]) > 1
      for: 1m
      labels:
        severity: warning