external:
  vm:
    write:
      url: https://monitoring-service.postgres.svc.cluster.local/victoriametrics/api/v1/write
vmagent:
  spec:
    externalLabels:
      k8s_cluster_id: minikube
vmalert:
  enabled: false
vmsingle:
  enabled: false
vmcluster:
  enabled: false