external:
  vm:
    write:
      url: https://monitoring-service.monitoring.svc.cluster.local/victoriametrics/api/v1/write
vmagent:
  spec:
    externalLabels:
      k8s_cluster_id: minikube
vmalert:
  enabled: false
grafana:
  enabled: false
prometheus-node-exporter:
  enabled: false
kube-state-metrics:
  enabled: false
vmsingle:
  enabled: false
vmcluster:
  enabled: false