external:
  vm:
    write:
      url: https://monitoring-service.monitoring.svc.cluster.local
vmagent:
  spec:
    externalLabels:
      k8s_cluster_id: minikube
grafana:
  enabled: false
prometheus-node-exporter:
  enabled: false
kube-state-metrics:
  enabled: false