external:
  vm:
    write:
      url: https://monitoring-service.postgres.svc.cluster.local/victoriametrics/api/v1/write
vmagent:
  spec:
    externalLabels:
      k8s_cluster_id: minikube
kube-state-metrics:
  volumeMounts:
    - name: crd-config
      mountPath: /etc/ksm/customresource-config
  volumes:
    - name: crd-config
      configMap:
        name: customresource-config-ksm

vmalert:
  enabled: false
vmsingle:
  enabled: false
vmcluster:
  enabled: false