backups:
  pgbackrest:
    configuration:
      - secret:
          name: postgres-pg-db-pgbackrest
    global:
      repo1-path: /pgbackrest/repo1
    repos:
      - name: repo1
        schedules:
          full: "0 0 * * 6"
          differential: "0 1 * * 1-6"
        volume:
          volumeClaimSpec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
pmm:
  enabled: true
  secret: postgres-pg-db-pmm-secret
  serverHost: https://monitoring-service.postgres.svc.cluster.local