apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/percona/percona-helm-charts.git
      path: charts/pg-operator
      targetRevision: HEAD
      helm:
        valueFiles:
          - $values/postgres/postgres-operator-values.yml
    - repoURL: https://github.com/percona/percona-helm-charts.git
      path: charts/pg-db
      targetRevision: HEAD
      helm:
        valueFiles:
          - $values/postgres/postgres-db-values.yml

    - repoURL: https://github.com/TurosIgor/argocd-practice.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: postgres
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true